### ISSUE TITLE
query-time road class filter selection

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#70]
the road class FrontierModel currently is parameterized at configuration time with the set of valid road classes. in order to explore different sets of valid road classes, we can optionally apply road class filtering based on a query `road_classes` argument.

**Comment by nreinicke** [comment]
> i should be in tomorrow if we want to have a real head-scratching discussion on this.

Yeah, I think it would be nice to sit down and talk through the best way to do this.

Some quick thoughts:

> is this more evidence that the map matching might need to be a fully-supported SearchApp module and somehow consolidated with the FrontierModel concept?

Yeah it is starting to feel like that and it's starting to feel like the FontierModel is actually either a FrontierModel or a GraphCorrelationModel (I hesitate to call it map matching since that term is used extensively with matching a trajectory to the graph). In Valhalla, they have two different models for correlating spatial input to the graph and for access (Loki and Sif, respectively).
